name: ${project.name}
version: ${project.version}
authors: [Alkarin]
description: Create Virtualplayers for debugging or running commands otherwise unavailable from the console
main: mc.alk.virtualplayers.VirtualPlayers
commands:
    virtualplayers:
        aliases: [vp,virtualplayer]
    ap:
        description: add virtual player
        usage: /ap  [arguments]
    vdc:
        aliases: [dc]
        description: do command as a virtual player
        usage: /dc [arguments]



