name: ${project.name}
version: ${project.version}
authors: [Alkarin, Europia79, BattlePlugins]
description: Create Virtualplayers for debugging or running commands otherwise unavailable from the console
main: mc.alk.virtualplayers.VirtualPlayers
api-version: 1.13
website: https://github.com/BattlePlugins/VirtualPlayers
commands:
    virtualplayers:
        aliases: [vp,vps,virtualplayer]
    ap:
        description: add virtual player
        usage: /ap  [arguments]
    vdc:
        aliases: [dc]
        description: do command as a virtual player
        usage: /dc [arguments]
