name: VirtualPlayers
version: 1.4.1.1
author: Alkarin
description: CraftBukkit_1.5.1. Create Virtualplayers for debugging or running commands otherwise unavailable from the console

main: mc.alk.virtualPlayer.VirtualPlayers
commands:
    virtualplayers:
        aliases: [vp,virtualplayer]
    ap:
        description: add virtual player
        usage: /ap  [arguments]
    vdc:
        aliases: [dc]
        description: do command as a virtual player
        usage: /dc [arguments]



